### ISSUE TITLE
Not able to use plugin in Intellij ultimate 2022.1.2

### ISSUE THREAD

**Issue by rverma-nsl** [jshiell/checkstyle-idea#576] opened 2022-06-06 02:07 UTC
Getting exception when using the default configuration as 10.3, works on 10.2
The scan failed due to an exception: null java.lang.NullPointerException   at org.infernus.idea.checkstyle.config.ConfigurationLocationSource.getConfigurationLocations(ConfigurationLocationSource.java:37)   at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:128)   at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:86)   at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)

**Comment by jeffryang24** [comment] 2022-06-06 08:06
Same... Also happened to me after upgrading the plugin version from 5.66.0 to 5.67.1, is there any regression?

**Comment by jshiell** [comment] 2022-06-06 17:26
Thanks for the report. The serialisation format changed, and it looks like a NPE was introduced where there was no module config active in one module - which, alas, I had activated via testing module changes. Should be fixed in 5.67.2.

**Closed by jshiell** 2022-06-06 17:26 UTC
