### ISSUE TITLE
Cyclic dependency error

### ISSUE THREAD

**Issue by testn** [jshiell/checkstyle-idea#330] opened 2017-07-11 18:59 UTC
```
Cannot init CheckStyle-IDEA component state: Cyclic dependency: [class org.infernus.idea.checkstyle.CheckstyleProjectService]
org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class org.infernus.idea.checkstyle.CheckstyleProjectService]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:75)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getInstance(CheckstyleProjectService.java:117)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.readCheckstyleVersion(CheckStyleConfiguration.java:358)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.toDto(CheckStyleConfiguration.java:332)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:311)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:27)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:329)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getInstance(CheckStyleConfiguration.java:476)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.<init>(CheckstyleProjectService.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getInstance(CheckstyleProjectService.java:117)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.readCheckstyleVersion(CheckStyleConfiguration.java:358)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.toDto(CheckStyleConfiguration.java:332)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:311)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:27)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:329)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getInstance(CheckStyleConfiguration.java:476)
	at org.infernus.idea.checkstyle.CheckStylePlugin.<init>(CheckStylePlugin.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:284)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:278)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:532)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$200(ProjectManagerImpl.java:70)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:479)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:476)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:603)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jshiell** [comment] 2017-07-11 19:13
Can you please tell me what version of the plugin you're using, and what version of IDEA?

**Comment by tsjensen** [comment] 2017-07-11 19:53
Looks like he's pre-5.8.1 ... *fingers crossed*

**Comment by testn** [comment] 2017-07-11 22:10
the latest one I just upgraded with Intellij IDEA 2017.2 EAP

**Comment by tsjensen** [comment] 2017-07-12 07:11
Duplicate of #327.
Please upgrade to the latest version of the plugin to get the fix.

**Comment by jshiell** [comment] 2017-07-12 08:58
Thanks @tsjensen. @testn please let us know if this doesn't fix it, and we'll take another look - thank you.

**Closed by jshiell** 2017-07-12 08:58 UTC

**Comment by testn** [comment] 2017-07-12 15:43
It seems to work so far. Thx.
