### ISSUE TITLE
MismatchedTokenException when writing new code

### ISSUE THREAD

**Issue by mikrobestie** [jshiell/checkstyle-idea#169] opened 2015-06-10 08:02 UTC
Hello,

after installing new version, I am receiving exceptions when writing code - code analysis is running while code is not completed so it's not compilable. Exceptions are like:

```
MismatchedTokenException occurred during the analysis of file C:\Users\kytyr\AppData\Local\Temp\csi-0d81885f-5d97-4dfe-a320-8f50a41ca193\src\main\java\cz\syntea\svj\app\component\AccessAdminComponent.java.: expecting EOF, found '}'
C:\Users\kytyr\AppData\Local\Temp\csi-0d81885f-5d97-4dfe-a320-8f50a41ca193\src\main\java\cz\syntea\svj\app\component\AccessAdminComponent.java:277:9: expecting EOF, found '}'
	at antlr.Parser.match(Parser.java:211)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:210)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:456)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:191)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
	at org.infernus.idea.checkstyle.CheckStyleInspection.scanFile(CheckStyleInspection.java:281)
	at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:227)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:151)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:427)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by jshiell** [comment] 2015-06-10 17:10
Hmm, that's very curious, as the plugin has always scanned when IDEA asks it to (and the code is often invalid at the time). I guess it could be a change in the new version of CheckStyle, or just an edge case I haven't seen before. In any case I'll have a look, but it's unlikely to be for at least a couple of weeks at present - sorry.

**Comment by jshiell** [comment] 2015-06-10 17:18
I've had a quick look - easy to reproduce, but it's a lot messier than I'd hoped. There are a lot of exceptions coming out of CheckStyle for invalid files now, and not just ANTLR exceptions, but NPEs.

My current thought is to catch all exception and just ignore them for the inspection, and continue to propagate them for the static scan. This will at least avoid problems during editing; however, it might lead to some bugs being missed thanks to the exception consumption. Lesser evil, I guess.

**Comment by jshiell** [comment] 2015-06-10 18:27
Well, that explains why you should never take a *quick* look at something. It's not propagated exceptions - the change is in CheckStyle, and it's logging these exceptions to commons-logging ERROR. Anything logged to ERROR ends up in the event log. And as IDEA controls the logging configuration, I can't even just turn CheckStyle logs off. And I'm strongly resistant to producing a patched version of CheckStyle just to avoid this.

So I'm not quite sure how to fix this immediately. It's not harmful, just irritating; I'd suggest downgrading if it's a problem until I come up with a solution.

**Comment by lwr** [comment] 2015-07-01 01:51
+1
Same issue we have.

Last a very long time, it is not harmful, but very annoying.

I have no idea if it's caused by plugin or JetBrains API changes.

**Comment by jshiell** [comment] 2015-07-01 05:54
> I have no idea if it's caused by plugin or JetBrains API changes.

It's caused by a change to logging in CheckStyle, and how IDEA handles logs that go via common logging. As CheckStyle now logs an error in this case it triggers IDEA's error handling. Apart from patching CheckStyle itself, I'm yet to come up with a workable solution. Suggestions welcomed.

**Comment by DidierLoiseau** [comment] 2015-07-01 07:11
Wouldn't it possible to check whether the file is syntactically correct
through IDEA's API before sending it to checkstyle?

Le mer. 1 juil. 2015 07:54, James Shiell <notifications@github.com> a
écrit :

**Comment by jshiell** [comment] 2015-07-01 07:33
Possibly. It'd be a slight performance hit. However, given IDEA's longstanding inability to determine the correctness of certain generic constructs I'm wary of introducing this, even beyond just complicating the code. I'd rather patch CheckStyle.

CheckStyle 6.8 is out so I may well kill two birds with one stone. I've been on holiday though, so nothing's likely to happen until this weekend at the easiest, once I'm over the jet lag.

**Comment by jshiell** [comment] 2015-07-01 20:09
My current solution is turning off logging for the TreeWalker class programmatically. God forfend IDEA ever drop Log4j without warning...

There's a [test build on DropBox](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.17.0.zip). It has only had cursory testing, but it appears to resolve this issue. It also includes CheckStyle 6.8.1.

**Comment by jshiell** [comment] 2015-07-03 20:11
Released in 4.17.0.

**Closed by jshiell** 2015-07-03 20:11 UTC

**Comment by DidierLoiseau** [comment] 2015-07-04 07:37
It seems that due to this change, problems in the configuration file are not logged in IDEA's event log: it only displays a quick popup with a truncated message:
![checkstyle-idea-treewalker-error](https://cloud.githubusercontent.com/assets/6871742/8506981/f53e4616-222f-11e5-9147-92c4b297de49.png)

(we had a configuration error where the `ParenPad` module was actually configured with the `RPAREN` token – I don't think it was reported in previous checkstyle versions)

**Comment by jshiell** [comment] 2015-07-04 08:17
I fear that'll be the case - TreeWalker catches errors for both the rules file parse an the source file parse, so both get suppressed from the error log (and log file, if active).

It does look like the error popup needs some love, though.

**Comment by jshiell** [comment] 2015-07-12 10:01
As of 4.17.2 I've modernised notifications, so that it should now display all the error text and also log it to the event log for later perusal.
