### ISSUE TITLE
NPEs in CheckStyle are incorrectly leaked to IDEA

### ISSUE THREAD

**Issue by flavor8** [jshiell/checkstyle-idea#127] opened 2014-12-21 13:27 UTC
ava.lang.NullPointerException
at com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck.visitToken(RightCurlyCheck.java:220)
at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:448)
at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:541)
at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:373)
at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:207)
at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:73)
at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:263)
at org.infernus.idea.checkstyle.CheckStyleInspection.scanFile(CheckStyleInspection.java:278)
at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:225)
at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:149)
at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:412)
at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:289)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:258)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:255)
at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:278)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by WonderCsabo** [comment] 2015-07-16 20:56
I am seeing this exception:

```
The inspection could not be executed.
org.infernus.idea.checkstyle.exception.CheckStylePluginException: The inspection could not be executed.
	at org.infernus.idea.checkstyle.CheckStylePlugin.processError(CheckStylePlugin.java:146)
	at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:208)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:151)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:427)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:200)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:38)
	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:358)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:276)
	at org.infernus.idea.checkstyle.CheckStyleInspection.scanFile(CheckStyleInspection.java:249)
	at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:195)
	... 22 more
```

I am not sure this is the same issue. These exceptions are not popping up when i run CS from the command line (from the maven-checkstyle-plugin).

**Comment by jshiell** [comment] 2015-07-17 07:46
This one looks to be different - it's coming out of CheckStyle, rather than the plugin.

What version of the plugin/CheckStyle are you using?

**Comment by WonderCsabo** [comment] 2015-07-17 07:52
I am using CS 6.8 and the latest version of the plugin.

**Comment by jshiell** [comment] 2015-07-18 18:05
The error seems to occur when the ThreadLocal ENTRIES hasn't been populated. So either there's something odd going on in CheckStyle, or there's something wrong with the threading in the plugin.

I've had a look through the plugin and can't spot anything immediately. While initialising of the Checker is run on a background thread, the actual scanning should all take place on the same thread, and hence the thread local in question should be initialised. However, the code is embarrassingly awful in this area so I'm putting some effort into tidying it up, in any case. So we'll see if that turns up anything.

**Comment by twbecker** [comment] 2015-07-27 14:11
FWIW I'm seeing the same exception as in WonderCsabos comment seemingly everytime the inspection tries to run.

**Comment by jshiell** [comment] 2015-07-27 14:12
@twbecker @WonderCsabo could one of you please attach your rules file/any suppression files? Thanks.

**Comment by WonderCsabo** [comment] 2015-07-27 14:14
@jshiell [here](https://github.com/WonderCsabo/androidannotations/blob/957_plugins/AndroidAnnotations/checkstyle-checks.xml) is mine.

**Comment by twbecker** [comment] 2015-07-27 14:17
I have a similar config wrt the suppessionFilter:

&lt;module name="SuppressionFilter">
      
      &lt;property name="file" value="${checkstyle.suppressions.file}" default="suppressions.xml"/>
&lt;/module>

I'll just add that checkstyle-idea does not properly default to the suppressions.xml file in our case - you have to explicitly configure it.

**Comment by twbecker** [comment] 2015-07-27 14:18
Here's the suppressions.xml file:

<?xml version="1.0"?>
   &lt;!DOCTYPE suppressions PUBLIC  "-//Puppy Crawl//DTD Suppressions 1.1//EN"     "http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
   &lt;suppressions>
     &lt;!-- Suppress all checks for generated sources -->
     &lt;suppress checks="." files="/generated-sources/"/>
   &lt;/suppressions>

**Comment by jshiell** [comment] 2015-07-27 14:20
Thanks both - I'll have a go with the debugger and see why we're not hitting the check init properly.

For the suppressions, from memory that element gets hacked around a bit to try and find it locally. It's possible something is going wrong wrt the default attribute - I'll check that as well.

**Comment by jshiell** [comment] 2015-07-27 19:48
I've had no immediate luck in reproducing it. What sort of value are you setting for the suppression file property (relative, absolute, examples gratefully received)? Anything else you can think of that would explain the discrepency?

On the `default` failure, mea culpa. Because the CheckStyle API doesn't let us modify elements, we have to remove and recreate them. Hence when we try to find the path for the suppression file (project relative, rules relative, etc) we fail to recreate the default element when we can't find the file. I've created #176 to track this, as it's not a five minute fix I fear.

**Comment by WonderCsabo** [comment] 2015-07-27 19:52
@jshiell i am setting an absolute path for the property. BTW, don't you have some sort of logging? Sending you the current input would help i guess.

**Comment by twbecker** [comment] 2015-07-27 19:54
In my case I've just set the value to the full path to the file shown above.  In my case, the exception always seems to happen while editing.

**Comment by WonderCsabo** [comment] 2015-07-27 19:54
@twbecker i also think this only happens while editing.

**Comment by twbecker** [comment] 2015-07-27 19:56
Ok I think I nailed it down.  At least for me it seems to happen when the source file won't parse properly.  Meaning if you delete a brace temporarily or start adding a code block that doesn't yet have a closing brace.

**Comment by WonderCsabo** [comment] 2015-07-27 19:58
@twbecker i cannot reproduce it currently. Can you provide us an example file and editing steps?

**Comment by twbecker** [comment] 2015-07-27 20:08
Ugh.  I've seen it about 20 times just writing code in a new class file, but I can't get a specific set of steps to reproduce.  Almost seems non-deterministic.

**Comment by jshiell** [comment] 2015-07-27 20:09
Bugger. I'll keep playing then, hopefully I'll hit it. Thanks!

**Comment by WonderCsabo** [comment] 2015-07-27 20:11
@jshiell if you would log the current input, we could send it to you when we hit this problem again. Or you can play. :)

**Comment by twbecker** [comment] 2015-07-27 20:12
Ok.  Closest I can get to steps to reproduce:

```java
public class Test {
    public static void main(String[] args) {
        private long foo;
        protected int bar = 1;
        //Put the caret immediately after int below and type a space, delete it then repeat.
        private int
    }

    public static class Inner {
        private Long baz;
    }
}
```

**Comment by WonderCsabo** [comment] 2015-07-27 20:16
@twbecker cool, i can reproduce it locally!

**Comment by jshiell** [comment] 2015-07-27 20:16
On the logging front, there's a bit but it's neglected and TBH I'm mostly ripping it out of new stuff. This is due to past problems in obtaining output, and in that usually I don't have problems reproducing it locally (and hence can play with the temporal stuff). Of course I could always be wrong on that :smile: It wouldn't be the first time.

In more amusing news, I've managed to get it to produce with you example above. Although oddly deleting the space did nothing. I switched away from the Window and immediately got an error logged. So I'll keep working on that example, as it's obviously triggering it somehow - thanks!

**Comment by jshiell** [comment] 2015-07-27 20:57
So end result is that it's due to the file being invalid. A `MismatchedTokenException` is thrown in `TreeWalker`. This is caught, but in doing so we skip over the `walk` calls, which initialise the aforementioned `ThreadLocal` in `SuppressWarningsHolder`. CheckStyle then bundles up the errors at the end of the check, and tests to see if the error is suppressed. At which points it blows up, as we never initialised the `ThreadLocal`.

Hence you'll never see it in CheckStyle outside of IDEA unless the file in invalid. So it's technically a CS bug, but one outside their normal use case.

So I shall have a think about how we can solve it in this case, which is likely to be catching it and filtering it out. Thanks very much to both of you for your help.

**Comment by WonderCsabo** [comment] 2015-07-27 21:01
You mean the file is invalid in a way that it cannot be parsed as a Java file, for example because of a missing ending brace? I think this should be definitely handled by CS itself. If so, an issue should be raised against CS.

**Comment by jshiell** [comment] 2015-07-27 21:04
True, and I will raise one, but I'd entirely understand why it wouldn't be a priority for them.

**Comment by jshiell** [comment] 2015-07-27 21:10
It looks like they're handling it in the `Main` class by just calling `System.exit` at the end. So any uncaught exceptions are ignored, and people just see the logged complaint (re the parse listener).

**Comment by jshiell** [comment] 2015-07-27 21:24
> Edit: i mean, can this happen for example with the maven-chekstyle-plugin or the command line CS tool, the ant task, or the Gradle plugin?

I believe it could, but it depends on how they handle exceptions that are leaked from the `Check.process` method.

Anyway, bug raised - I'll have a look at a nice way to suppress this, hopefully tomorrow night.

**Comment by twbecker** [comment] 2015-07-28 00:12
> True, and I will raise one, but I'd entirely understand why it wouldn't be a priority for them.
Was it not a CS upgrade that caused this?  Seems like if it's a regression that should be reason enough for them to fix.

**Comment by jshiell** [comment] 2015-07-28 20:53
Fair point. In any case the bug is raised and we'll see what they say - they've been pretty good in the past with getting bugs sorted, so fingers crossed.

**Comment by jshiell** [comment] 2015-07-28 21:30
Test build: https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.17.3.zip

I'd appreciate it if you are able to give this a quick test. It seems to be working for me - I can see the NPEs being logged, but they're no longer triggering a check failure. Otherwise, I'll hopefully be able to give it a bit more testing and a release tomorrow night.

**Comment by WonderCsabo** [comment] 2015-07-28 21:43
I tested it with the class contributed by @twbecker , and it seems your fix indeed works.

**Comment by twbecker** [comment] 2015-07-29 12:40
Seems to work here also.  Thanks for the quick turnaround (as usual)!

**Comment by jshiell** [comment] 2015-07-29 17:01
My pleasure. Thanks both for your help - it would have taken much, much longer without it!

**Closed by jshiell** 2015-07-29 17:01 UTC

**Comment by jshiell** [comment] 2015-08-08 15:40
@twbecker as an outcome of my inventions of the *default* attribute problem (#176) it should work as it is. However, the property must be entirely unset (i.e. blank in the configuration property table) for the default to be used. CheckStyle does the parsing, and never exposes the value of the default attribute in the object tree the plugin gets - it merely has the file attribute with either the entered value or, if the property in the file value isn't resolvable, the default value.

Hence there's no ability to fall back to the default value if the file value is unresolvable (well, not without parsing the rules file again, ourselves).
