### ISSUE TITLE
 java.lang.ClassCastException: antlr.CommonHiddenStreamToken cannot be cast to antlr.Token

### ISSUE THREAD

**Issue by MCMicS** [jshiell/checkstyle-idea#449] opened 2019-07-09 09:43 UTC
With the last updates of Idea and the plugin I get following error. If I press reload config it work for an short time but then it appears again.
OS: Windows
IDEA: 2019.1.3

```
org.infernus.idea.checkstyle.exception.CheckstyleToolException: Exception was thrown while processing Foo.java
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:136)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
	at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$6(ScanFiles.java:190)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:190)
	at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:149)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:75)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:31)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:339)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Foo.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	... 13 more
Caused by: java.lang.ClassCastException: antlr.CommonHiddenStreamToken cannot be cast to antlr.Token
	at antlr.CharScanner.makeToken(CharScanner.java:173)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_CONTENT(GeneratedJavaLexer.java:1258)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_BEGIN(GeneratedJavaLexer.java:1199)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:335)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:158)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:97)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:160)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 18 more
```

**Comment by jshiell** [comment] 2019-07-09 09:57
Does this happen with Checkstyle on the command line as well? That exception does look like it's coming out of the parser in Checkstyle rather than from the plugin.

**Comment by MCMicS** [comment] 2019-07-09 10:01
not tested yet.
but we have a job on buildsystem to use checkstyle as commandline and there are no errors.
Maybe it is some library in IDE classpath which causes the conflict

**Comment by jshiell** [comment] 2019-07-09 10:03
It wouldn't be the first time that's happened. I certainly can't find any relevant bug in Checkstyle's list. 

Could you please attach your rules file? I'll try have a look at this ASAP, although it'll probably be this weekend at the earliest. I don't have a Windows box either, but it doesn't look like a platform issue 🤞

**Comment by MCMicS** [comment] 2019-07-09 10:08
thanks for look.

[rules.zip](https://github.com/jshiell/checkstyle-idea/files/3372449/rules.zip)

**Comment by jshiell** [comment] 2019-07-10 15:56
Stupid thought - did this happen while you were editing a file, e.g. might the file have been syntacticly incorrect at the time?

Checkstyle only commit to supporting syntactically correct files - the output for anything unparsable is unpredictable, by design (i.e. it just propagates whatever happens). As such, plugin authors need to do some extra error handling to catch these cases, and every so often a new variation pops up that breaks this. Hence I'm wondering if this might be one of those cases.

**Comment by MCMicS** [comment] 2019-07-10 15:59
Yes most of them occurs if I edit a file. And IDea saves automatically and an check could be run in background

**Comment by jshiell** [comment] 2019-07-10 16:00
Smashing, thanks - hopefully a fix shouldn't be too hard in this case.

**Comment by MCMicS** [comment] 2019-07-10 16:01
could you reproduce it while editing files?

**Comment by jshiell** [comment] 2019-07-10 16:01
Haven't tried as yet, this was just from thinking through the problem on my commute.

**Comment by MCMicS** [comment] 2019-07-10 16:04
I thought this is not the main problem. Now I get the message too if I change nothing but switching between files.
Sorry for that bad news

**Comment by jshiell** [comment] 2019-07-10 16:41
All is not yet lost - it's definitely hitting this case, having traced it, although it may be hitting another case as well.

And it's quick to fix, so I can get this out now (5.29.1) and - assuming problems continue - can investigate further when I've more time to hand.

**Comment by MCMicS** [comment] 2019-07-10 16:50
ok thanks. I will try it as soon as possible

**Comment by jshiell** [comment] 2019-07-10 16:52
Thanks - no rush, mind - looks like the weekend is the earliest I'll get time to have another go 😄

**Comment by MCMicS** [comment] 2019-07-11 16:32
I've updated the plugin but a new error occurs.
But this is not happen so many times like before

2019-07-11 17:31:38,534 [27599292]   WARN - a.checkstyle.checker.ScanFiles - An error occurred while scanning a file. 
```
org.infernus.idea.checkstyle.exception.CheckStylePluginParseException: Exception was thrown while processing Foo.java
	at org.infernus.idea.checkstyle.service.ExceptionWrapper.wrap(ExceptionWrapper.java:34)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:132)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
	at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$6(ScanFiles.java:190)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:190)
	at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:149)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:75)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:31)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:339)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Foo.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	... 13 more
Caused by: java.lang.ClassCastException: antlr.CommonHiddenStreamToken cannot be cast to antlr.Token
	at antlr.CharScanner.makeToken(CharScanner.java:173)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_CONTENT(GeneratedJavaLexer.java:1258)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_BEGIN(GeneratedJavaLexer.java:1199)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:335)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:158)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:97)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:160)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 18 more
```

**Comment by jshiell** [comment] 2019-07-13 10:27
Where are you seeing the exception? That looks like the log file?

An exception will be logged - we've received an error from the plugin, and have no definite way of differentiating an exception caused by a programming error (e.g. the plugin or Checkstyle has broken) and one caused by unparsable input. Hence we'd log it, and it should be present in the event log and in the IDEA log files - but it shouldn't cause an uncaught exception (i.e. the flashing red icon in the bottom right of the IDE window).

The alternative would be to hide it, which would a) hide real errors and b) make it looks like the scan wasn't happening at all.

**Comment by MCMicS** [comment] 2019-07-13 10:28
the log appears in error log within ide

**Comment by jshiell** [comment] 2019-07-13 10:31
Hmm. Are you able to share a sample of code which produces this? I've managed to produce similar traces, but haven't managed the `ClassCastException` exactly yet. 

I appreciate this may not be possible for confidentiality/commercial reasons, of course.

**Comment by MCMicS** [comment] 2019-07-13 10:33
I can try to reproduce it eith sample caode but the original code (commercial) cannot be shared
it occurs in many files. After your fix mostly before commit to SVN (with check with checkstyle)

**Comment by jshiell** [comment] 2019-07-13 10:53
That's perfect - that's what I was missing. I was presuming it was occurring with the real-time scan, as parse problems tend to be linked to code being edited. It doesn't look like we're handling this case for on-commit scans, as we expect the code to be parseable. 

Which raises the question of what to do with this. Checkstyle itself is throwing the error, so we have a choice of either continuing to raise it as an error, or of suppressing it on the basis that the user knows what they're doing. What do you think?

**Comment by jshiell** [comment] 2019-07-13 11:02
And there's a third option, which I'm working on now - which is to clean up the error output so it's clear as to the cause, e.g.

<img width="1301" alt="Screen Shot 2019-07-13 at 12 01 52" src="https://user-images.githubusercontent.com/1030482/61170761-0aec0d00-a566-11e9-9edc-b86cc1b543f3.png">

**Comment by jshiell** [comment] 2019-07-13 11:17
Error recording changes have been released in 5.29.2.

**Comment by MCMicS** [comment] 2019-07-13 11:57
Thanks I will try it monday on work

But to clarify:
The first error " antlr.CommonHiddenStreamToken cannot be cast to antlr.Token" occurs during runtime checks if editing files or switching editors with valid files.
After 5.29.1 the error mostly occurs during pre commit check but sometimes at runtime.

I use OpenJDK 11 and java11 sources.
Maybe this is another hint.

**Comment by MCMicS** [comment] 2019-07-15 15:35
Tested the new version on work.
The error within IDE Event Log occurs if I change a file and the file is checked (either during runtime or by click 'Check Current Change List'.

```
17:28	The source file could not be parsed by Checkstyle
			The scan failed due to a parse error: Exception was thrown while processing Foo.java
			Root cause:
			antlr.CommonHiddenStreamToken cannot be cast to antlr.Token
			java.lang.ClassCastException: antlr.CommonHiddenStreamToken cannot be cast to antlr.Token

			at antlr.CharScanner.makeToken(CharScanner.java:173)

			at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_CONTENT(GeneratedJavaLexer.java:1258)

			at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mBLOCK_COMMENT_BEGIN(GeneratedJavaLexer.java:1199)

			at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:335)

			at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)

```
The Checkstyle Window the show that the file is unparsable for a time. If I click ''Check Current Change List' again, the check may works then.
It seems that the Check is not possible for a while after change file content. (may be until Idea has build index for changed content)
I I wait a time

**Comment by jshiell** [comment] 2019-07-18 17:48
Hmm. I've made no progress on this. The file logic is consistent for the checks - for each file we check if it is either not yet on the disk, or unsaved and, if so, we create a temporary file and scan that. Otherwise we scan using the file on disk. Either way, this logic is run before the scan takes place (in `ScannableFile`), so there should be no time lag. 

Purely speaking in theory it could be related to indexing - we rely on IDEA's API to get the file metadata and decide how to scan it, but it seems odd.

**Comment by jshiell** [comment] 2019-07-18 17:58
Thank you. I fear my environment may not be a good match for this, as I've only small projects to work with, and an entirely different OS with a different filesystem and approach to file locking. 

🤞

**Comment by MCMicS** [comment] 2019-07-18 18:00
Is there anyway to enable debug logging for your plugin to help for looking the cause?

**Comment by MCMicS** [comment] 2019-07-18 18:11
Thanks
I will try it if can reproduce it.
But if seem to work with versions before 2019.1.2
Maybe its a version problem but we will see if if reproduce it.

But this will not happen before monday. But then i will try it

**Comment by jshiell** [comment] 2019-07-18 18:18
Hmm, odd if it does work before 2019.1.2 - there's nothing I'm aware of that should change behaviour in that case.

**Comment by MCMicS** [comment] 2019-07-19 07:51
[CheckStyle_Error.zip](https://github.com/jshiell/checkstyle-idea/files/3409979/CheckStyle_Error.zip)

I have created a simple sample. May be occurs only if one rule exists with properties. Without the rule the error not occurs so easy.
I uploaded a zip. Maybe one of the plugins interfers with yours.

My Version: IDEA 2019.1.3
Build #-IU-191.7479.19

Steps to reproduce:
1. Checkout Project
2. Add rule within src/main/resources
3. set property to project root
4. Goto SampleValue class and remove `private long second;`
5. click Check Current file (may be two or three time)


Github: https://github.com/MCMicS/CheckStyle_Error

**Comment by jshiell** [comment] 2019-07-19 15:25
Thanks - I'll try have a poke at this this weekend.

**Comment by jshiell** [comment] 2019-07-22 07:25
I made no progress on this during the weekend I fear, as events intervened, but it's top of my todo list for plugin work.

**Comment by MCMicS** [comment] 2019-07-22 10:02
Hi. No Problem.

**Comment by jshiell** [comment] 2019-07-28 10:24
Bad news - I can't reproduce on either 2019.1.3 or 2019.2. I can happily spam the `scan current file` button and it seems fine. So either I'm going very wrong, or this is an issue specific to Windows (which wouldn't be entirely surprising, given how different the IO stacks are).

Does it still occur for your on 2019.2?

I'm also going trying updating the API we build against from 2017 to 2018, just in case there were any relevant deprecations.

**Comment by MCMicS** [comment] 2019-07-28 10:29
I've last week and now I am at holiday for some days. I will have a look with the 2019.2 update.

But this could be done in about 2 weeks

**Comment by jshiell** [comment] 2019-07-28 10:30
No rush - I hope you have a good holiday!

**Comment by MCMicS** [comment] 2019-08-01 12:14
Hi,
I've tested it with 2019.2 and the error still occurs :(

So it's maybe a Windows specific problem.

**Comment by MCMicS** [comment] 2019-08-02 09:35
Got a better message now.
Maybe it help to find a solution.

```
The scan failed due to a parse error: Exception was thrown while processing Foo.java
			Root cause:
			class antlr.CommonHiddenStreamToken cannot be cast to class antlr.Token (antlr.CommonHiddenStreamToken is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @56d9833e; antlr.Token is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @443f2233)
			java.lang.ClassCastException: class antlr.CommonHiddenStreamToken cannot be cast to class antlr.Token (antlr.CommonHiddenStreamToken is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @56d9833e; antlr.Token is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @443f2233)

			at antlr.CharScanner.makeToken(CharScanner.java:173)
```

**Comment by jshiell** [comment] 2019-08-03 10:53
I fear it doesn't tell us a lot more, other than module info for Java 9+. The `ChildFirstURLClassLoader` is actually our main line of defence against class path issues - it ensures we check the local (i.e. Checkstyle) class path before delegated to the IDEA class path (which does have conflicting versions of some dependencies). 

I'm kind of at a dead end tbh, given I can't reproduce it, and given that IDEA 2018.2.x works fine with the same code. I didn't spot anything even vaguely relevant when updating to the 2018 SDK, and I can't justify an upgrade to the 2019 SDK at present (as that will cut off users using IDEA 2018 - and I suspect it's probably a red herring anyway). 

I did have a quick poke around https://youtrack.jetbrains.com but can't spot anything relevant. Mind, I've never had much searching on that thing. 

The only thought I had is that it's odd for an issue like this to only be seen by one person, which does make me wonder if there's something unusual in your setup which is changing things. Does the problem still occur if you disable all other third-party plugins, for instance? And it is Windows 10 you're using, I presume?

**Comment by MCMicS** [comment] 2019-08-03 11:49
Ok.
I can try a clean Installation with checkstyle plugin only

**Comment by MCMicS** [comment] 2019-08-05 07:11
I had installed another checkstyle plugin (QAPlug).
Maybe this was the cause. I've removed it and have a look if the error is gone.

**Comment by MCMicS** [comment] 2019-08-05 15:40
The errot not occurs for now. So I thought it was the other plugin.
I close this issue.

**Comment by MCMicS** [comment] 2019-08-05 17:01
Now I got them again after check from the commit dialog. Then it comes on normal usage too.

**Comment by jshiell** [comment] 2019-08-06 15:55
To be fair it would have been a bit odd, as IDEA is fairly consistent on classpath isolation.

**Comment by MCMicS** [comment] 2019-08-06 16:23
I've looked in my other plugin and only the PMD plugin contains additional antlr libs.
I try to remove this and try it again.
I know it seems odd. But yesterday the error occurs only after commit to SVN.

**Comment by zielint0** [comment] 2019-11-19 09:26
I had this bug multiple times on 5.34.0.
After IDEA restart it is gone.

**Comment by MCMicS** [comment] 2019-11-19 09:33
After Restart the errors are gone but they occurs after time of working with IDE

**Comment by jshiell** [comment] 2019-11-19 12:37
This is generally caused by changes in how the core Checkstyle library handles (or doesn't handle) errors. Can you please tell me which version of Checkstyle you are using, and also provide a stack trace from the errors?

**Comment by MCMicS** [comment] 2019-11-19 12:47
I can try to get the stacktrace. Because the error is non-reproducible it is difficult to get the stack. But after long work time with IDE occurs.

I've tested it with Checkstyle 8.22 and 8.26

**Comment by MCMicS** [comment] 2019-11-19 14:50
Got the exception again (checkstyle 8.26). This was happen from the svn commit dialog with enabled checkstyle check before commit. I've got an dialog that there was checkstyle error (can choose between Review, Cancel or Commit).
After click on Commit I saw the error in Event Log

I have an screenshot of the balloon:
![Stacktrace error](https://user-images.githubusercontent.com/4604206/69156396-9b71c580-0ae3-11ea-9b02-56218ce03c3e.jpg)
```
Root cause:
class antlr.CommonHiddenStreamToken cannot be cast to class antlr.Token (antlr.CommonHiddenStreamToken is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @423461cf; antlr.Token is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @62f20787)
java.lang.ClassCastException: class antlr.CommonHiddenStreamToken cannot be cast to class antlr.Token (antlr.CommonHiddenStreamToken is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @423461cf; antlr.Token is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @62f20787)
  at antlr.CharScanner.makeToken(CharScanner.java:173)
  at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.mIDENT(GeneratedJavaLexer.java:1743)
  at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:391)
  at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
  at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
  at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
  at antlr.TokenBuffer.fill(TokenBuffer.java:69)
  at antlr.TokenBuffer.LA(TokenBuffer.java:80)
  at antlr.LLkParser.LA(LLkParser.java:52)
  at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:158)
  at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
  at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:328)
  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
  at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)
  at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
  at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
  at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
  at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
  at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
  at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$7(ScanFiles.java:197)
  at java.base/java.util.Optional.map(Optional.java:265)
  at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:197)
  at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:156)
  at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:78)
  at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:32)
  at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:322)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
```

> IntelliJ IDEA 2019.2.4 (Ultimate Edition)
> Build #IU-192.7142.36, built on October 29, 2019

**Comment by jshiell** [comment] 2019-11-19 14:51
Thank you!

**Comment by MCMicS** [comment] 2019-11-19 14:54
You're welcome.
Hope it helps to identify the checkstyle error

**Comment by jshiell** [comment] 2019-11-28 17:12
Right, I remain clueless. So, I've added some debug to this one. If you enable debug on the appropriate path (**Help** -> **Debug Log Settings...**, and add `#org.infernus.idea.checkstyle.checker.CheckStyleChecker`) then the IDEA log (**Help** -> **Show Log in Finder**) should print a debug statement whenever we create a new Checker, e.g.

```
2019-11-28 17:06:51,333 [ 128830]  DEBUG - tyle.checker.CheckStyleChecker - Creating Checkstyle instances with CheckStyle classpath:
URLClassLoader: org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/classes/
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/checkstyle-8.25.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/picocli-4.0.4.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/antlr-2.7.7.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/antlr4-runtime-4.7.2.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/commons-beanutils-1.9.4.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/guava-28.1-jre.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/Saxon-HE-9.9.1-5.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/commons-collections-3.2.2.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/failureaccess-1.0.1.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/jsr305-3.0.2.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/checker-qual-2.8.1.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/error_prone_annotations-2.3.2.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/j2objc-annotations-1.3.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/checkstyle/lib/animal-sniffer-annotations-1.18.jar
- url=file:/Users/jshiell/Projects/checkstyle-idea/test-configs/cp-test.jar
UrlClassLoader: com.intellij.ide.plugins.cl.PluginClassLoader
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/slf4j-log4j12-1.7.25.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/slf4j-api-1.7.25.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/log4j-1.2.17.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/checkstyle-idea-5.34.0.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/jcl-over-slf4j-1.7.25.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/commons-codec-1.11.jar
- url=file:/Users/jshiell/Library/Application%20Support/IntelliJIdea2019.2/CheckStyle-IDEA/lib/commons-io-2.6.jar
```
If you're able to capture the state of this when it's in an error state then hopefully that will shed some light on what's going on.

[CheckStyle-IDEA-5.34.0-debug](https://www.dropbox.com/s/5kfvz965s9haeck/CheckStyle-IDEA-5.34.0-debug.zip?dl=0)

**Comment by MCMicS** [comment] 2019-11-28 18:08
I will enable it tomorrow

**Comment by MCMicS** [comment] 2019-12-16 08:34
Hi. Today at 9:22 the error occurs again two times.
Then I clicked Build and the error is gone.

The log is attached
[checkstyle-idea_Crash.log](https://github.com/jshiell/checkstyle-idea/files/3966752/checkstyle-idea_Crash.log)

**Comment by jshiell** [comment] 2019-12-16 08:35
Thanks! I'm off next week, so will take another stab at it 🤞

**Comment by MCMicS** [comment] 2019-12-16 11:01
thanks.
I had a hort look on the log output but found no difference between both calls

**Comment by jshiell** [comment] 2019-12-27 15:26
I, unfortunately, concur. I see no difference between these that could lead to this sort of problem. And the whole point of the child-first classloader is to avoid the chance of hitting nasties further down the chain.

I fear there's something important that I'm missing here - class path problems should generally be pretty deterministic. It's not like we're changing the JARs accessible to the classpath unless we change the Checkstyle version. I'll keep thinking.

**Comment by jshiell** [comment] 2024-03-29 15:12
Closed due to no further updates, and that by now we're dealing with meaninfully different components.

**Closed by jshiell** 2024-03-29 15:12 UTC
