### ISSUE TITLE
New Icons in 5.89.0 too large

### ISSUE THREAD

**Issue by mscott-tw** [jshiell/checkstyle-idea#637] opened 2024-03-27 15:10 UTC
After updating the checkstyle version (to 5.89.0), it looks like there is an issue with the new icons (mentioned in the release notes), in that the checkstyle icon at the bottom of the IDE is now very large. 

The screenshot attached shows the space it's now taking up. 

![Screenshot from 2024-03-27 17-08-32](https://github.com/jshiell/checkstyle-idea/assets/25585288/d8040e02-f0f6-4e34-aaa6-0b465dfd56f2)

**Comment by jshiell** [comment] 2024-03-27 15:29
Oh dear, definitely related as I switched to SVGs. It doesn’t seem to be scaling it - so hopefully just a matter of changing the default size.

Out of interest - what platform are you on? As it is working correctly on my setup (latest release, latest mac os).

**Comment by jshiell** [comment] 2024-03-27 16:11
Hopefully fixed in 5.89.1, _hopefully_ given I couldn't reproduce it. However, the default icon sizes now match the IDEA docs rather than relying on the UI to do the right thing.

**Closed by jshiell** 2024-03-27 16:11 UTC

**Comment by bramblevine** [comment] 2024-03-27 17:44
Thanks for the quick turnaround on this one. I can confirm upgrading to 5.89.1 fixes the icon size for me running Intellij Ultimate 2023.3.6 on Ubuntu 20.04 with the old UI.

**Comment by mscott-tw** [comment] 2024-03-28 07:19
Also confirming the latest version fixes the issue, thanks for working on the plugin and the speedy fix!

**Comment by soleetions** [comment] 2024-03-28 08:05
Issue is now also fixed for the MacOS (14.3) version of IntelliJ 2023.3.6
