### ISSUE TITLE
NoViableAltException: Live Scan seems to stumble over special strings

### ISSUE THREAD

**Issue by Scrayos** [jshiell/checkstyle-idea#485] opened 2020-03-25 23:48 UTC
First of all, I'm sorry if this error is already known, I did my best to search for existing errors, as I thought that it's impossible that no one already reported it, but I failed to find such an Issue, so that's why I'm here.

This error started to occur a few months ago and does not completely prevent me from using this plugin, but certainly is a hindrance.

The plugin seems to not be able to handle "special" strings within the source code. And by special I mean strings that get a special treatment by IntelliJ IDEA (Ultimate). This includes at least SQL Statements and Regular Expressions, but I'm pretty sure that I've also seen a similar exception for the "package"-keyword at the start of the file. But since this only occured sporadic, let's focus on the other two, as they are affected 100% of the time.

Each tested file can be scanned just fine without any findings in the dedicated window and also checking without this plugin, with the normal Checkstyle.jar works aswell. The only affected component seems to be the live-scanner of this plugin. If there's any more information that could help to identify the cause, please let me know!

**IntelliJ IDEA version:** IntelliJ IDEA 2019.3.3 (Ultimate Edition)
**Plugin version:** 5.35.8
**Checkstyle version:** 8.30
**Java version:** 13.0.2

<details>
  <summary>SQL statements</summary>

```
Checkstyle: Ein Fehler ist aufgetreten - com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred while parsing file /tmp/csi-233/DatabaseStreamIterator.java.
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
    at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:43)
    at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$1(CheckStyleInspection.java:114)
    at java.base/java.util.Optional.map(Optional.java:265)
    at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:114)
    at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:64)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834) 
Caused by: /tmp/csi-233/DatabaseStreamIterator.java:1:1: unexpected token: SELECT
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99) ... 20 moreCheckstyle: 
```

[![Image from Gyazo](https://i.gyazo.com/c9e94bd559e0b5ac6ddd19fc56b275c6.png)](https://gyazo.com/c9e94bd559e0b5ac6ddd19fc56b275c6)
</details>

<details>
  <summary>RegEx</summary>

```
Checkstyle: Ein Fehler ist aufgetreten - com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred while parsing file /tmp/csi-254/CommandHandler.java.
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
    at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:43)
    at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$1(CheckStyleInspection.java:114)
    at java.base/java.util.Optional.map(Optional.java:265)
    at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:114)
    at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:64)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834) 
Caused by: /tmp/csi-254/CommandHandler.java:1:1: unexpected token: (
    at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99) ... 20 more
```

[![Screenshot from Gyazo](https://gyazo.com/804e90d8a3654edaadaa9c0683dd7f93/raw)](https://gyazo.com/804e90d8a3654edaadaa9c0683dd7f93)
</details>

Also the stacktrace is always printed twice, if that helps:
[![Screenshot from Gyazo](https://gyazo.com/3803aa2db96254c76fc6902990dd8a7f/raw)](https://gyazo.com/3803aa2db96254c76fc6902990dd8a7f)

Also: Thank you for your work! This plugin is great and makes it easier for our new team members to adapt our styleguides and coding conventions!

**Comment by jshiell** [comment] 2020-03-26 08:06
Morgen! Thanks for the report - that's a new one on me. 

The interesting bit is that the exception is coming from the Checkstyle parser - it's not coming from the plugin. However, there's a change - because Checkstyle is not designed to handle syntactically invalid files, we dump the IDEA file to disk before passing it to Checkstyle for the live scan. If the file is incorrect at the time of the scan (e.g. mismatched quote) then Checkstyle will throw something like this. In most cases we capture it and hide it - but every so often a change in Checkstyle will produce a new error case that we don't handle. 

That's one possibility - I'll try have a look at the handling code and see if this is handled.

However, it's not a complete fit - as I wouldn't expect this to only occur within special strings. So another option is that IDEA is doing something odd internally with these strings, and hence our dump to disk may be doing something odd.

To help with the latter case, could you please try and dump one of the temp files (e.g. `/tmp/csi-285/CommandHandler.java` or similar) when the error next occurs, and check if it matches the source code, or if something odd has occurred? Thank you!

**Comment by Scrayos** [comment] 2020-03-26 12:11
It wasn't all that easy to dump the contents of these files, as they are – as you probably already knew – deleted right after the scan. So I had to use `fswatch` in conjunction with `tail` to get the content. 

This however, fortunately pointed me to something that is also worth noting: 
If I open the file CommandHandler (in the IDE), there are indeed two scan files, that are created/modified/deleted. e.g.:
```
/tmp
/tmp/csi-014
/tmp
/tmp/csi-015
/tmp
/tmp/csi-014
/tmp
/tmp/csi-014
/tmp
/tmp/csi-014
/tmp
/tmp/csi-014
/tmp
/tmp/csi-015
/tmp
/tmp/csi-015
/tmp
/tmp/csi-015
/tmp
/tmp/csi-015
```

When I monitored the content of said files in parallel, there was another surprising result. Both files seemed to contain the same content: `(?: (.*))?` – Only the Regular Expression, no other source code at all.

That being said, it is possible, that this was only the "end-result" of said files. As you can see from the output of `fswatch` above, there were probably multiple edits for those files, so maybe they originally contained the whole files and were during the process edited to only contain the expression.

**Comment by jshiell** [comment] 2020-03-26 13:23
Magic, thanks - that suggests that something odd is going on, as I wouldn't expect those segments to result in individual files. I'll have a look, hopefully this weekend 🤞

**Comment by jshiell** [comment] 2020-03-29 11:16
I'm pretty sure this is two separate issues:

a) ANTLR is throwing a parse exception that we didn't recognise, and hence were not suppressing. This should be fixed in today's release, and I've made the code a bit more robust about catching ANTLR exceptions.

b) we're also capturing embedded language segments and scanning them. I suspect this may have been happening a while, and needs further investigation.

I hope the fix to (a) will be enough to stop the constant exceptions and make life a bit more pleasant for you while I poke at (b).

**Comment by Scrayos** [comment] 2020-03-29 16:52
Thanks for this update and the great communication regarding this issue. I'm really overwhelmed by your helpful responses and the maintenance you put into this project!

The update however, sadly hasn't resolved the errors at the reported segments. I made extra sure that this wasn't related to my setup and asked a friend of mine, that never installed the plugin before to install the newest version and test it with a really short code-snippet of `Pattern.compile("(?: (.*))?");` within the main-Method of an otherwise empty project. It sadly still occurs on his PC aswell.

**Comment by jshiell** [comment] 2020-03-29 17:01
Bugger. You're far too kind given I've failed to fix it 😄 

I've obviously missed something - sorry! Thanks for the quick feedback, and I'll have another go as soon as I can.

**Comment by jshiell** [comment] 2020-03-30 16:18
I'm having problems reproducing it at present, even with the example above I can't get it to break. Could you please attached your rules file, if possible? 

My setup, for the record: MacOS 10.13.6; IDEA 2019.3.4 Ultimate on runtime 11; Checkstyle 8.30; plugin at head. So it should be pretty close, given this should all execute in the runtime JVM, not the project JVM.

What I have learnt in the meantime is that the `LocalInspectionTool` appears to iterate over the injected elements and passes them to the inspection for scanning; what I can't work out is why they're not being filtered out by the sanity check.

**Comment by Scrayos** [comment] 2020-03-30 17:04
The rule file I'm using is publicly available here: https://scrayosnet.pages.dev.scrayos.net/SuperCompanyPOM/checkstyle.config.xml

My setup is the following:
**OS:** Arch Linux with kernel 5.5.13-arch1-1
**IJ IDEA:** Ultimate, now also at 2019.3.4
**Runtime version:** 11.0.6+8-b520.43 amd64
**VM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o
**Checkstyle:** 8.30
**Plugin:** 5.35.9

My collegue didn't respond yet, but I'm pretty sure he's on Windows, so it's probably not related to the setup but the config instead. The config is very ... extensive, as you'll see. I spent a lot of time writing it, so it is totally possible, that some specific option or an arbitrary combination between those options is the cause of the error.

That would also explain why no one reported this here yet. I was so sure, that it would probably already be known, because we had these errors for quite a while now. But of course we've also used this config for the whole time. 

I'll have a look into when a member of my team first asked me about those errors to maybe track back on which change could've caused it in Git. Thankfully we're using chats, so it should be possible, although quite challenging. I update our config with every checkstyle update, so it could actually boil down to a single change introduced by me. I'll let you know if I find out anything.

**Comment by jshiell** [comment] 2020-03-30 17:07
Thank you, that's perfect! Please don't spent too much time chasing - hopefully this'll allow me to reproduce, and once I've got that then hopefully I can make some progress!

**Comment by jshiell** [comment] 2020-03-30 17:14
<img width="845" alt="Screen Shot 2020-03-30 at 18 12 20" src="https://user-images.githubusercontent.com/1030482/77941459-1b8a1200-72b2-11ea-99ab-64784850b3dd.png">

That did the trick - I managed to reproduce it with your rule file and my changing the scan scope to `all files in project`. I'm pretty much out of time for tonight, but that gives me a great place to start digging into it - thanks!

**Comment by Scrayos** [comment] 2020-03-30 17:17
You're welcome! Our scan scope is also set to `all files in project`. Here's my full config, just in case: 

[![Image from Gyazo](https://i.gyazo.com/bee0ede564d1a277597fc18c293a7977.png)](https://gyazo.com/bee0ede564d1a277597fc18c293a7977)

**Comment by jshiell** [comment] 2020-03-30 17:37
Right, definitely out of time, but I know the cause - just not sure of the fix yet.

The problem is that the `PsiFile` that gets passed to us for the injected RegEx (or otherwise) retains the file name of the parent file. Hence we get a Regex file called `TestClass.java`. As the scan scope is set to everything we don't filter it out by type (Regex), and the temporary file uses the filename when writing to disk. So when Checkstyle sees the file, it thinks it's a Java file, tries to parse it ... and the rest is history.

Initial thoughts are either a) don't write out injected elements or b) try and infer a filetype from the type, but that could fast get complicated ... anyway, some progress at least.

**Comment by tsjensen** [comment] 2020-03-31 13:08
Just a thought: The *semantics* of the scan scope "All files in project" were that we wanted to cover all files that you can see in the repo. So, regex snippets are not really included in that, and also wouldn't make much sense, because Checkstyle as a tool is not aware of them. In fact, I think regex snippets didn't exist back when I added that feature.

In other words, it could be OK to just filter them out *even* when the scan scope is set to "All files in project".

I don't know enough about the IDEA API though, so I can't predict if that's sufficient. (Are they still part of the original Java file as a String? etc.)

**Comment by jshiell** [comment] 2020-03-31 13:17
Possibly, although it raises a question as to what else we filter out/in. I'm tending towards just filtering all snippets out tbh, as Checkstyle operates on a file level.

**Comment by Scrayos** [comment] 2020-03-31 14:30
> Possibly, although it raises a question as to what else we filter out/in. I'm tending towards just filtering all snippets out tbh, as Checkstyle operates on a file level.

Yeah, that's also the approach that I find the most desirable. It's absolutely not needed to check those Snippets individually, but they should certainly be checked as a part of the original file. That way I could still develop (for example) an own Checkstyle-Rule that requires the Keywords of SQL-Statements to be written in uppercase.

**Comment by jshiell** [comment] 2020-03-31 16:07
I'm pretty sure I have it this time - could you please give this build a try before I commit and make another fool of myself? ;-) Thanks!

https://github.com/jshiell/checkstyle-idea/releases/tag/5.36.1

**Comment by Scrayos** [comment] 2020-03-31 20:04
Yeah, seems to work just fine! I tested it with the reproduction snippet and my original example classes for RegEx aswell as SQL statements. Thank you very much for your work!

**Comment by jshiell** [comment] 2020-04-01 06:45
My pleasure - thank you very much for your help and patience!

**Closed by jshiell** 2020-04-01 06:45 UTC
