### ISSUE TITLE
8.24 Checkstyle files not backward compatible

### ISSUE THREAD

**Issue by horwitzj** [jshiell/checkstyle-idea#454] opened 2019-09-02 19:35 UTC
e.g., `LineLength` checks are under `TreeWalker` for 8.23 but under `Checker` for 8.24—if a project's XML uses 8.24, then the Intellij plugin will not be able to parse the XML file (and, thus, will not be usable).

(See [release notes](https://checkstyle.org/releasenotes.html#Release_8.24).)

**Comment by jshiell** [comment] 2019-09-02 21:06
Sorry, I'm a bit confused as to what the issue is here...? There are multiple versions of Checkstyle that break backwards compatibility, which is why we support multiple versions. As long as you have the correct version of Checkstyle active for the given rules file then there should be no issues.

**Comment by horwitzj** [comment] 2019-09-02 21:12
Sorry about being unclear. Specifically, when I use Checkstyle 8.24—and update the XML file as necessary—the plugin (understandably) doesn't work:
```The Checkstyle rules file could not be parsed.
				LineLength is not allowed as a child in Checker
				The file has been blacklisted for 60s.```

Essentially, it appears that the plugin won't work with my projects until it supports 8.24 (this has not been a problem with previous Checkstyle upgrades, at least not for me).

And, by the way—thanks a lot for this great plugin!

**Comment by jshiell** [comment] 2019-09-02 21:52
Smashing, thanks for the clarification! I'll try and add 8.24 support later this week.

**Comment by jshiell** [comment] 2019-09-03 16:59
And released as 5.32.0. Enjoy!

**Closed by jshiell** 2019-09-03 16:59 UTC

**Comment by mpalourdio** [comment] 2019-10-04 10:53
@jshiell Hello,

Looks like your latest releases do not fix this particular problem. I have update the plugin to 5.33.0 + checkstyle in my pom.xml to 8.25 + my checktyle xml file to move `LineLength` from `TreeWalker` to `Checker`, but intellij still complains about ` LineLength is not allowed as a child in Checker`

Any tip on how I can give you more information ?

Here is my checktyle configuration file : https://raw.githubusercontent.com/mpalourdio/configuration/master/checkstyle.xml

Thanks for all your work here !

**Comment by jshiell** [comment] 2019-10-04 10:54
Did you change to 8.25 in the plugin preferences?

**Comment by mpalourdio** [comment] 2019-10-04 10:56
Wow, I was not aware of this configuration part, as all has always worked out of the box. I have just changed, I will let you know !

**Comment by mpalourdio** [comment] 2019-10-04 11:00
@jshiell Indeed, it obviously fixes the problem ! Thanks a lot.

**Comment by jshiell** [comment] 2019-10-04 11:01
Excellent news, and you’re very welcome!
