### ISSUE TITLE
IntelliJ won't open after installing latest update

### ISSUE THREAD

**Issue by alansegar-hb** [jshiell/checkstyle-idea#495] opened 2020-06-29 10:11 UTC
IntelliJ Ultimate (latest version) on Windows 10 Pro no longer opens after installing the latest Checkstyle update when prompted this morning. 
- IntelliJ opened my existing project as normal this morning
- Clicked the prompt within IntelliJ to update the Checkstyle plugin
- Clicked the prompt after install completed to restart IntelliJ to activate the change
- IntelliJ gets stuck during loading with "Loading ***** Project" dialog with a progress bar (not moving) and a Cancel button
- Cancel button does nothing.
- No longer able to use IntelliJ at all.

UPDATE
- following steps in https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000524244-Disable-Uninstall-plugin-without-launching-Idea?page=1#community_comment_360001687339 I've deleted the CheckStyle-IDEA folder under C:/users/{user}/.IntelliJIdea2019.3/config/plugins and the IDE opens again now.
I'm using version 2020.1 but the folder has a different version number (probably due to having updated from an older version in the past)

**Comment by jshiell** [comment] 2020-06-29 11:02
I presume it works again once you've deleted the plugin? 

2020.1.2 is fine here (Mac OS) so not sure what could be going on. Is there anything in the log file?

**Comment by alansegar-hb** [comment] 2020-06-29 11:25
It does work again after deleting the plugin.
I can't see anything obvious in the main log file but there are several threadDump files in 
C:\Users\{user}\AppData\Local\JetBrains\IntelliJIdea2020.1\log\threadDumps-freeze-20200629-103742-IU-201.7846.76
which contain stacktraces starting as follows:

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@766d2b9f
	at java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock(ReadMostlyRWLock.java:249)

```
further down there's a section mentioning XMLExtensionAdapter
```
"ApplicationImpl pooled thread 12" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter@14b0cf97 owned by "BuildManager Pool[ApplicationImpl pooled thread 10]" Id=30
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.isInstanceCreated(XmlExtensionAdapter.java:38)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:444)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:401)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:232)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at com.intellij.openapi.projectRoots.SdkType.getAllTypes(SdkType.java:234)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.findSdkTypeByName(ProjectJdkTableImpl.java:295)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.getSdkTypeByName(ProjectJdkTableImpl.java:290)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.readExternal(ProjectJdkImpl.java:161)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.loadState(ProjectJdkTableImpl.java:316)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:63)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:16)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:438)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:138)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:103)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:50)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:358)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:58)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:188)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at com.intellij.openapi.projectRoots.ProjectJdkTable.getInstance(ProjectJdkTable.java:22)
	at org.jetbrains.kotlin.idea.util.IjPlatformUtil$getProjectJdkTableSafe$1.invoke(ijPlatformUtil.kt:13)
	at org.jetbrains.kotlin.idea.util.IjPlatformUtil$getProjectJdkTableSafe$1.invoke(ijPlatformUtil.kt)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:880)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:28)
```
searching those files for "Checkstyle" doesn't report any matches.

**Comment by jshiell** [comment] 2020-06-29 11:28
Thanks. Those don't shine any light, I fear - they don't appear to be related to the plugin in any way.

This is doubly curious as the only change to the plugin that would affect its loaded is moving from the depreacted module configuration process - which was loaded at startup - to the current one, which shouldn't even be touched until you open the appropriate panel

**Comment by jshiell** [comment] 2020-06-30 09:19
I fear I haven't found anything on this; and we've had no other reports of it so far. Without further information or the ability to reproduce it I fear I'm pretty much stuck.

**Comment by alansegar-hb** [comment] 2020-06-30 09:32
Thanks for looking. I've just tried an uninstall from within the plugins section of IntelliJ (this was needed even after manually deleting the folder yesterday to get the IDE to open again).
Then a reinstall of the plugin followed by enabling it.
IntelliJ then prompted to restarted and after that the latest version of the plugin is installed and appears to be working (I can see at least one warning against a line in a file if I deliberately introduce an issue that I know Checkstyle normally detects).

**Comment by jshiell** [comment] 2020-07-04 12:56
That's good news at least. 

I've still no ideas on this one - I can't even think of a reason for IDEA to do this, the plugin aside. I'll leave this open for a bit to see if we do get any more reports, however.

**Comment by jshiell** [comment] 2021-04-06 16:33
Closing due to no further reports 😅

**Closed by jshiell** 2021-04-06 16:33 UTC
