### ISSUE TITLE
checkstyle exception due to renamed configuration file

### ISSUE THREAD

**Issue by erikdw** [jshiell/checkstyle-idea#307] opened 2017-05-15 09:27 UTC
I renamed my checkstyle configuration file from the command line.  The plugin was very unhappy with this since it had a reference to a nonexistent file.  I wasn't able to edit the existing file path in the IntelliJ preferences to remedy the situation (see #309). This issue also coincided with an infinite repeating "indexing" cycle in IntelliJ.

Versions:

* IntelliJ 15.0.6
* Checkstyle-IDEA 5.5.0

Exception:

```
Failed to resolve properties for Storm Checkstyle
java.lang.RuntimeException: Failed to resolve properties for Storm Checkstyle
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.cloneCommonPropertiesTo(ConfigurationLocation.java:342)
	at org.infernus.idea.checkstyle.model.FileConfigurationLocation.clone(FileConfigurationLocation.java:319)
	at org.infernus.idea.checkstyle.ui.PropertiesPanel.setConfigurationLocation(PropertiesPanel.java:92)
	at org.infernus.idea.checkstyle.ui.PropertiesDialogue.setConfigurationLocation(PropertiesDialogue.java:96)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$EditPropertiesAction.actionPerformed(CheckStyleConfigPanel.java:388)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:404)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:399)
	at com.intellij.ui.ToolbarDecorator$3.doEdit(ToolbarDecorator.java:441)
	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:72)
	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1638)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1587)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:99)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:106)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:184)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:104)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:263)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:254)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jshiell** [comment] 2017-05-20 13:20
I've been unable to reproduce the looping indexing issue - when I renamed the current rules file I get continued warnings that the file can't be found, which build up in a stacked alert box. The only difference I can spot here is that I'm using 2017.1.3, which certainly has improved alert feedback over earlier versions. Support for IDEA 15 remains on a basis that there haven't been any API breakages, so I fear if it's a 15-specific issue it's very unlikely to be addressed by myself. Sorry.

There are certainly some UI issue around the editing of files - something I missed is that newer versions of IDEA now ignore the action properties when setting the add/edit/remove actions, and hence the tooltips on the buttons don't indicate their actual functionality (e.g. the edit button used to have a tooltip of `Edit the properties of the selected configuration`) - however, while the API allows changing the name of the buttons, the tooltip does not appear to be exposed. So to address this it's likely to require a rethink of how we communicate this via the UI - or extend the edit dialogue to allow the path to be changed. At present it's not a high priority for me (I'm basically just keeping the plugin spinning, as it's not something I've actively used myself in years) so again, unlikely to be changed it he near future. It's certainly something I'll bear in mind in case I do end up doing some other work in this area, though.

Thanks for your feedback, and apologies for the constant disappointment I'm delivering.

**Closed by jshiell** 2017-05-20 13:20 UTC

**Comment by erikdw** [comment] 2017-05-30 04:48
@jshiell : haha, no worries.  I understand the frustration of having unreproducible problems.
