### ISSUE TITLE
IntelliJ IDEA Dark Themes

### ISSUE THREAD

**Issue by DavidSoles** [jshiell/checkstyle-idea#516] opened 2021-02-25 03:59 UTC
I found the checkstyle plugin for IntelliJ IDEA very useful but the it doesn't seen to play very well with dark themes. Each line background is gray. Here is an example.

![image](https://user-images.githubusercontent.com/984410/109100955-39e3d200-76fc-11eb-8572-3d488617e408.png)

But in the problems tab looks fantastic.

![image](https://user-images.githubusercontent.com/984410/109100989-49631b00-76fc-11eb-8d9c-14628091b3d3.png)

Thanks for the plugin.

**Comment by pbludov** [comment] 2021-02-25 08:30
I've been using the Dracula theme for many years and it works just fine for me:
![image](https://user-images.githubusercontent.com/900805/109123175-9675da00-775a-11eb-807a-2857bebe9345.png)

**Comment by jshiell** [comment] 2021-02-28 12:39
Thanks for the report. I can't reproduce this with Darcula on IDEA 2020.3.2U/Mac OS. What platform are you on, and what theme are you using?

This code does use a custom tree node renderer; however, it should set the background via colours obtained from the `UIManager` (`Tree.selectionBackground`, `Tree.textBackground`). So it may well be an issue specific to the platform/theme.

**Comment by jshiell** [comment] 2021-04-08 11:41
Closing due to no further information, and inabilty to reproduce with Darcula.

**Closed by jshiell** 2021-04-08 11:41 UTC
