### ISSUE TITLE
NullPointerException occurs with checkstyle configuration file

### ISSUE THREAD

**Issue by dongjinleekr** [jshiell/checkstyle-idea#256] opened 2016-07-05 06:46 UTC
Hello. I am experiencing NPE when I try to import the checkstyle config file for Java code formatter. The configs I am trying to import are:

https://github.com/apache/giraph/blob/trunk/checkstyle.xml
https://github.com/apache/giraph/blob/trunk/checkstyle-relaxed.xml
https://github.com/apache/giraph/blob/trunk/checkstyle-relaxed-8.xml

And the detailed description of my installation is like following:

- Ubuntu 16.04 LTE
- IntelliJ IDEA 2016.1.3
- Build #IU-145.1617, built on June 3, 2016
- JRE: 1.8.0_76-release-b198 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- CheckStyle-IDEA 4.30.0

Could you check above files? Thanks in advance.

**Comment by jshiell** [comment] 2016-07-05 18:51
Hey - thanks for your report.

I was able to load all three problems and scan with them without problems. This is using IDEA 15 & 2016 and the latest code (should match 4.30.0).

The only problem I did get was if I tried to add the file without specifying a value for the `checkstyle.header.file` property, in which case I got an exception trace (as below) which doesn't indicate the problem at all. So that needs a fix, certainly.
{code}
org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be loaded.</b><br>unable to parse configuration stream<br>The file has been blacklisted for 60s.</html>
	at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAndShowMessage(CheckerFactory.java:215)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:170)
{code}

Could you please attach the NPE trace, and I'll trace it through and see what pops out?

**Comment by dongjinleekr** [comment] 2016-07-08 05:08
Hmm, it seems like it gave any logs - I could find nothing from my installation. What all I get was Error message like the attached image.

![checkstyle](https://cloud.githubusercontent.com/assets/2375128/16675924/881356a4-4500-11e6-9934-73a0d8529808.png)

OK. I will re-test it with explicit checkstyle.header.file configuration. I thought it would work well with its default value (LICENSE.txt), for that file already exists.

**Comment by jshiell** [comment] 2016-07-08 06:48
Ah, I misunderstood - I missed the code formatter part - sorry! I'll retest again with that. (The code formatter was a contribution, so I tend to forget about it on occasion ... mea culpa.)

**Comment by jshiell** [comment] 2016-07-08 18:00
Indeed it wasn't being logged - I ended up slapping the debugger on it to find the cause. There was no property resolver being attached during import, so the moment it hit a property - boom. I've now changed it to just resolve every property to an empty string, which I believe will be enough for our purposes here.

This fix is in 4.30.1, which should be released later this weekend. Thanks very much for the report and for your help!

**Closed by jshiell** 2016-07-08 18:00 UTC
